//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerReadingsDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowerMeterDemoEntities : DbContext
    {
        public PowerMeterDemoEntities()
            : base("name=PowerMeterDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Measure> Measures { get; set; }
        public virtual DbSet<Reading> Readings { get; set; }
        public virtual DbSet<ReadingLKP> ReadingLKPs { get; set; }
    }
}
