//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerReadingsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingLKP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadingLKP()
        {
            this.Readings = new HashSet<Reading>();
        }
    
        public int Id { get; set; }
        public int MeaasureID { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> Threshold { get; set; }
    
        public virtual Measure Measure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reading> Readings { get; set; }
    }
}
